version: '3.0'
services:
    stockmanager:
        image: adautomendes/stock-manager
        ports:
            - 8080:8080
        container_name: stockmanager
        networks:
            - inatel
        depends_on:
            - mysql
    mysql:
        image: mysql
        ports:
            - 3306:3306
            - 33060:33060
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bootdb
        networks:
            - inatel
        container_name: mysql
    quotation-management:
        build:
            context: ./QuotationManagement
            dockerfile: Dockerfile.dev
        container_name: quotation-management
        ports:
          - 8081:8081
        environment:
          - SERVER_HOST=quotation-management
          - SERVER_PORT=8081
          - MYSQL_HOST=mysql
          - MYSQL_PORT=3306
          - STOCK_MANAGER_HOST=stockmanager
          - STOCK_MANAGER_PORT=8080
          - SPRING_PROFILES_ACTIVE=prod
        depends_on:
          - stockmanager
          - mysql
        networks:
          - inatel
networks:
    inatel:
        name: inatel